(()=>{
const KEY='rumo_app_v4';
const getDb=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const today=()=>new Date().toISOString().slice(0,10);
const days=d=>{if(!d)return null;return Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000)};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
function refreshDashboard(){const db=getDb();if(!db||!document.querySelector('#dashboardView')||document.querySelector('#dashboardView').classList.contains('hidden'))return;const ds=Array.isArray(db.demandas)?db.demandas:[],total=ds.length,done=ds.filter(x=>x.status==='Concluída').length,progress=ds.filter(x=>x.status==='Em andamento').length,late=ds.filter(x=>x.due_date&&x.due_date<today()&&x.status!=='Concluída'&&x.status!=='Cancelada').length,due7=ds.filter(x=>{const n=days(x.due_date);return n>=0&&n<=7&&x.status!=='Concluída'&&x.status!=='Cancelada'}).length;const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=v};set('#total',total);set('#done',done);set('#progress',progress);set('#late',late);set('#due7',due7);set('#donutTotal',total);set('#legendLate',`${late} (${total?Math.round(late/total*100):0}%)`);set('#legendDue',`${due7} (${total?Math.round(due7/total*100):0}%)`);set('#legendProgress',`${progress} (${total?Math.round(progress/total*100):0}%)`);set('#legendDone',`${done} (${total?Math.round(done/total*100):0}%)`);const table=document.querySelector('#demandTable');if(table){const q=(document.querySelector('#search')?.value||'').toLowerCase(),sf=document.querySelector('#statusFilter')?.value||'';const list=ds.filter(x=>(!sf||x.status===sf)&&(!q||[x.title,x.unit,x.owner,x.status].join(' ').toLowerCase().includes(q)));table.innerHTML=list.map(x=>`<tr><td>${esc(x.id)}</td><td><b>${esc(x.title)}</b></td><td>${esc(x.unit||'—')}</td><td>${esc(x.owner||'')}</td><td>${esc(x.due_date||'—')}</td><td><span class="status-pill ${x.status==='Concluída'?'ok':x.status==='Em andamento'?'warn':'open'}">${esc(x.status)}</span></td><td>${days(x.due_date)??'—'}</td></tr>`).join('')||'<tr><td colspan="7">Nenhuma demanda encontrada.</td></tr>'}
const unitList=document.querySelector('#unitList');if(unitList){const counts={};ds.forEach(x=>{const key=String(x.unit||'').trim().toLowerCase();if(key)counts[key]=(counts[key]||0)+1});const units=Array.isArray(db.unidades)?db.unidades.filter(u=>u&&u.active!==false):[];const names=[...new Map([...units.map(u=>[String(u.name||'').trim().toLowerCase(),u]),...Object.keys(counts).filter(k=>!units.some(u=>String(u.name||'').trim().toLowerCase()===k)).map(k=>[k,{name:k}])]).values()];const max=Math.max(1,...names.map(u=>counts[String(u.name||'').trim().toLowerCase()]||0));unitList.innerHTML=names.map(u=>{const name=String(u.name||'').trim(),n=counts[name.toLowerCase()]||0;return `<div class="unit-row"><span>${esc(name)}</span><div class="bar"><i style="width:${n?Math.max(8,Math.round(n/max*100)):0}%"></i></div><b>${n}</b></div>`}).join('')||'<div class="unit-row"><span>Nenhuma unidade</span><b>0</b></div>'}}
}
const run=()=>{refreshDashboard();if(location.hash==='#demandas'&&typeof window.RUMO_REFRESH==='function')window.RUMO_REFRESH()};
document.addEventListener('click',e=>{if(e.target.closest('[data-view]'))setTimeout(run,120)});window.addEventListener('hashchange',()=>setTimeout(run,120));setInterval(run,2000);setTimeout(run,500);
})();