(()=>{
const C=window.RUMO_SUPABASE_CONFIG,KEY='rumo_app_v4',UNITDEL='rumo_deleted_units_v1';
if(!C)return;
const base=C.url+'/rest/v1/';
const headers=(upsert=false)=>({'apikey':C.key,'Authorization':'Bearer '+C.key,'Content-Type':'application/json','Prefer':upsert?'resolution=merge-duplicates,return=representation':'return=representation'});
const api=async(path,opts={})=>{const r=await fetch(base+path,{...opts,cache:'no-store',headers:{...headers(!!opts.upsert),...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?[]:r.json()};
const nativeSet=(k,v)=>Storage.prototype.setItem.call(localStorage,k,v);
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const getDeletedUnits=()=>{try{return JSON.parse(localStorage.getItem(UNITDEL)||'[]').map(String)}catch{return[]}};
const normalizeUnits=db=>{if(!db)return db;const deleted=new Set(getDeletedUnits()),seen=new Set(),out=[];(db.unidades||[]).forEach(u=>{if(deleted.has(String(u.id)))return;let name=String(u.name||'').trim(),city=String(u.city||'').trim(),state=String(u.state||'').trim().toUpperCase();if(!name)return;if(name.toLowerCase()==='campo grande'){name='Campo Grande';city='Campo Grande';state='MS'}if(/^\d{4}-\d{2}-\d{2}$/.test(state))state=city.slice(0,2).toUpperCase();const key=name.toLowerCase();if(seen.has(key))return;seen.add(key);out.push({id:u.id,name,city,state,active:u.active!==false})});db.unidades=out;return db};
const syncUnits=async()=>{let db=normalizeUnits(read());if(!db)return;const deleted=new Set(getDeletedUnits());for(const id of deleted){if(/^\d+$/.test(id))await api('units?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:{Prefer:'return=minimal'}})}const units=db.unidades.filter(u=>u.name&&!deleted.has(String(u.id))).map(u=>({name:u.name,city:u.city||'',state:u.state||'',active:u.active!==false}));if(units.length)await api('units?on_conflict=name',{method:'POST',upsert:true,body:JSON.stringify(units)});const server=(await api('units?select=id,name,city,state,active&order=id')).filter(u=>!deleted.has(String(u.id)));db.unidades=server;nativeSet(KEY,JSON.stringify(db));};
const captureSubmit=e=>{const f=e.target;if(!(f instanceof HTMLFormElement)||!f.closest('#moduleDialog'))return;const title=f.querySelector('h3')?.textContent||'';if(!/unidades/i.test(title))return;e.preventDefault();e.stopImmediatePropagation();const data=Object.fromEntries(new FormData(f));(async()=>{try{await api('units?on_conflict=name',{method:'POST',upsert:true,body:JSON.stringify({name:data.name.trim(),city:data.city.trim(),state:data.state.trim().toUpperCase(),active:true})});await syncUnits();f.closest('dialog')?.close();alert('Unidade salva no Supabase.')}catch(err){console.error(err);alert('Não foi possível salvar no Supabase.')}})()};
document.addEventListener('submit',captureSubmit,true);
setTimeout(()=>syncUnits().catch(e=>console.warn('Supabase unit sync:',e)),800);
})();