(()=>{
const KEY='rumo_app_v4';
const getDb=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const nativeSet=(db)=>Storage.prototype.setItem.call(localStorage,KEY,JSON.stringify(db));
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const isUnitsPage=()=>document.querySelector('#workspace h1')?.textContent?.trim()==='Unidades Rumo';
const sbDelete=async id=>{const C=window.RUMO_SUPABASE_CONFIG;if(!C||!id)throw new Error('Supabase indisponível');const r=await fetch(C.url+'/rest/v1/units?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:{apikey:C.key,Authorization:'Bearer '+C.key,Prefer:'return=minimal'}});if(!r.ok)throw new Error(await r.text())};
function addCss(){if(document.querySelector('#unidades-delete-css'))return;const s=document.createElement('style');s.id='unidades-delete-css';s.textContent='.unit-actions{display:flex;gap:6px;align-items:center}.mini.danger-unit{border-color:#efb7be!important;color:#c52f40!important;background:#fff7f8!important}.mini.danger-unit:hover{background:#ffecee!important;border-color:#e29aa4!important}';document.head.appendChild(s)}
function render(){if(!isUnitsPage())return;addCss();const db=getDb()||{},data=Array.isArray(db.unidades)?db.unidades:[],head=document.querySelector('#moduleHead'),body=document.querySelector('#moduleBody');if(!head||!body)return;head.innerHTML='<tr><th>NOME DA UNIDADE</th><th>CIDADE</th><th>UF</th><th>STATUS</th><th>AÇÕES</th></tr>';const q=(document.querySelector('#moduleSearch')?.value||'').toLowerCase();const list=data.filter(x=>!q||[x.name,x.city,x.state].join(' ').toLowerCase().includes(q));body.innerHTML=list.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.city||'—')}</td><td>${esc(x.state||'—')}</td><td><span class="status-pill ${x.active===false?'cancel':'ok'}">${x.active===false?'Inativa':'Ativa'}</span></td><td class="unit-actions"><button class="mini" type="button" data-unit-edit="${esc(x.id)}">Editar</button><button class="mini danger-unit" type="button" data-unit-delete="${esc(x.id)}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-row">Nenhuma unidade encontrada.</td></tr>';body.querySelectorAll('[data-unit-edit]').forEach(b=>b.onclick=()=>window.__RUMO_OPEN_RECORD&&window.__RUMO_OPEN_RECORD('unidades',b.dataset.unitEdit));body.querySelectorAll('[data-unit-delete]').forEach(b=>b.onclick=()=>deleteUnit(b.dataset.unitDelete));const stats=document.querySelector('#moduleStats');if(stats)stats.innerHTML=`<div><small>Total</small><strong>${data.length}</strong></div><div><small>Ativas</small><strong>${data.filter(x=>x.active!==false).length}</strong></div><div><small>Inativas</small><strong>${data.filter(x=>x.active===false).length}</strong></div>`}
async function deleteUnit(id){const db=getDb()||{},i=(db.unidades||[]).findIndex(x=>String(x.id)===String(id));if(i<0)return;const u=db.unidades[i];if(!confirm(`Excluir a unidade “${u.name||id}”?\n\nEssa ação não poderá ser desfeita.`))return;try{if(u.id)await sbDelete(u.id);db.unidades.splice(i,1);nativeSet(db);alert('Unidade excluída com sucesso.');window.location.reload()}catch(e){console.error(e);alert('Não foi possível excluir esta unidade. Se ela possuir demandas vinculadas, remova ou altere essas demandas antes de excluir.')}}
function bind(){if(!isUnitsPage())return;addCss();const action=document.querySelector('#moduleAction');if(action&&!action.dataset.unitBound){action.dataset.unitBound='1';const original=action.onclick;action.onclick=()=>{if(typeof original==='function')original()}}render();const search=document.querySelector('#moduleSearch');if(search&&!search.dataset.unitSearchBound){search.dataset.unitSearchBound='1';search.oninput=render}}
const schedule=()=>setTimeout(bind,80);document.addEventListener('click',e=>{if(e.target.closest('[data-view]'))schedule()});window.addEventListener('hashchange',schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();
})();