(()=>{
const KEY='rumo_app_v4',DELKEY='rumo_deleted_units_v1';
const getDb=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const nativeSet=db=>Storage.prototype.setItem.call(localStorage,KEY,JSON.stringify(db));
const getDeleted=()=>{try{return new Set(JSON.parse(localStorage.getItem(DELKEY)||'[]').map(String))}catch{return new Set()}};
const isUnitsPage=()=>document.querySelector('#workspace h1')?.textContent?.trim()==='Unidades Rumo';
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]||c));
const getUnits=()=>{const db=getDb()||{},del=getDeleted(),seen=new Set();return (db.unidades||[]).filter(u=>u&&u.name&&!del.has(String(u.id))).filter(u=>{const k=String(u.name).trim().toLowerCase();if(seen.has(k))return false;seen.add(k);return true})};
function renderUnits(){if(!isUnitsPage())return;const us=getUnits(),q=(document.querySelector('#moduleSearch')?.value||'').toLowerCase(),list=us.filter(u=>[u.name,u.city,u.state].join(' ').toLowerCase().includes(q));const stats=document.querySelector('#moduleStats'),head=document.querySelector('#moduleHead'),body=document.querySelector('#moduleBody');if(stats)stats.innerHTML=`<div><small>Total</small><strong>${us.length}</strong></div><div><small>Ativos/abertos</small><strong>${us.filter(u=>u.active!==false).length}</strong></div><div><small>Última atualização</small><strong>Agora</strong></div>`;if(head)head.innerHTML='<tr><th>Nome da unidade</th><th>Cidade</th><th>UF</th><th>Ações</th></tr>';if(body)body.innerHTML=list.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.city||'—')}</td><td>${esc(u.state||'—')}</td><td><div class="unit-actions"><button class="mini" data-edit="${esc(u.id)}">Editar</button><button class="mini danger-unit" data-unit-delete="${esc(u.id)}">Excluir</button></div></td></tr>`).join('')||'<tr><td colspan="4">Nenhuma unidade cadastrada.</td></tr>';if(body){body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const db=getDb()||{},u=(db.unidades||[]).find(x=>String(x.id)===String(b.dataset.edit));if(u&&typeof window.RUMO_UNIT_EDIT==='function')window.RUMO_UNIT_EDIT(u)});body.querySelectorAll('[data-unit-delete]').forEach(b=>b.onclick=()=>deleteUnit(b.dataset.unitDelete))}}
window.RUMO_UNITS_RENDER=renderUnits;
const sbDelete=async id=>{const C=window.RUMO_SUPABASE_CONFIG;if(!C||!id)throw new Error('Supabase indisponível');const r=await fetch(C.url+'/rest/v1/units?id=eq.'+encodeURIComponent(id),{method:'DELETE',cache:'no-store',headers:{apikey:C.key,Authorization:'Bearer '+C.key,Prefer:'return=minimal'}});if(!r.ok)throw new Error(await r.text())};
async function deleteUnit(id){const db=getDb()||{},i=(db.unidades||[]).findIndex(x=>String(x.id)===String(id));if(i<0)return;const u=db.unidades[i];if(!confirm(`Excluir a unidade “${u.name||id}”?\n\nEssa ação não poderá ser desfeita.`))return;try{await sbDelete(u.id);const del=getDeleted();del.add(String(u.id));db.unidades.splice(i,1);nativeSet(db);Storage.prototype.setItem.call(localStorage,DELKEY,JSON.stringify([...del]));renderUnits();alert('Unidade excluída com sucesso.')}catch(e){console.error(e);alert('Não foi possível excluir esta unidade. Se ela possuir demandas vinculadas, remova ou altere essas demandas antes de excluir.')}}
window.RUMO_UNIT_EDIT=u=>{const md=document.querySelector('#moduleDialog');if(!md)return;const old=u||{};md.innerHTML=`<form class="module-form"><h3>Editar — unidades</h3><label>Nome da unidade<input name="name" value="${esc(old.name||'')}" required></label><label>Cidade<input name="city" value="${esc(old.city||'')}" required></label><label>UF<input name="state" value="${esc(old.state||'')}" maxlength="2" required></label><div class="actions"><button type="button" class="ghost" id="closeUnitEdit">Cancelar</button><button>Salvar</button></div></form>`;md.showModal();document.querySelector('#closeUnitEdit').onclick=()=>md.close();md.querySelector('form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),C=window.RUMO_SUPABASE_CONFIG;try{const r=await fetch(C.url+'/rest/v1/units?id=eq.'+encodeURIComponent(old.id),{method:'PATCH',cache:'no-store',headers:{apikey:C.key,Authorization:'Bearer '+C.key,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({name:d.name.trim(),city:d.city.trim(),state:d.state.trim().toUpperCase(),active:true})});if(!r.ok)throw new Error(await r.text());const db=getDb()||{};db.unidades=(db.unidades||[]).map(x=>String(x.id)===String(old.id)?{...x,name:d.name.trim(),city:d.city.trim(),state:d.state.trim().toUpperCase(),active:true}:x);nativeSet(db);md.close();renderUnits();alert('Unidade atualizada com sucesso.')}catch(err){console.error(err);alert('Não foi possível atualizar a unidade.')}}};
const schedule=()=>setTimeout(renderUnits,80);document.addEventListener('click',e=>{if(e.target.closest('[data-view="unidades"]'))schedule()});window.addEventListener('hashchange',schedule);window.addEventListener('storage',e=>{if(e.key===KEY||e.key===DELKEY) schedule()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();setInterval(()=>{if(isUnitsPage())renderUnits()},1500);
})();