(()=>{
const KEY='rumo_app_v4';
const getDb=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const nativeSet=db=>Storage.prototype.setItem.call(localStorage,KEY,JSON.stringify(db));
const isUnitsPage=()=>document.querySelector('#workspace h1')?.textContent?.trim()==='Unidades Rumo';
const sbDelete=async id=>{const C=window.RUMO_SUPABASE_CONFIG;if(!C||!id)throw new Error('Supabase indisponível');const r=await fetch(C.url+'/rest/v1/units?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:{apikey:C.key,Authorization:'Bearer '+C.key,Prefer:'return=minimal'}});if(!r.ok)throw new Error(await r.text())};
function addCss(){if(document.querySelector('#unidades-delete-css'))return;const s=document.createElement('style');s.id='unidades-delete-css';s.textContent='.unit-actions{display:flex;gap:6px;align-items:center}.mini.danger-unit{border-color:#efb7be!important;color:#c52f40!important;background:#fff7f8!important}.mini.danger-unit:hover{background:#ffecee!important;border-color:#e29aa4!important}';document.head.appendChild(s)}
function addDeleteButtons(){if(!isUnitsPage())return;addCss();const body=document.querySelector('#moduleBody');if(!body)return;body.querySelectorAll('tr').forEach(row=>{const edit=row.querySelector('[data-edit]'),actions=edit?.parentElement;if(!edit||!actions||actions.querySelector('[data-unit-delete]'))return;actions.classList.add('unit-actions');const del=document.createElement('button');del.type='button';del.className='mini danger-unit';del.dataset.unitDelete=edit.dataset.edit;del.textContent='Excluir';del.onclick=()=>deleteUnit(del.dataset.unitDelete);actions.appendChild(del)})}
async function deleteUnit(id){const db=getDb()||{},i=(db.unidades||[]).findIndex(x=>String(x.id)===String(id));if(i<0)return;const u=db.unidades[i];if(!confirm(`Excluir a unidade “${u.name||id}”?\n\nEssa ação não poderá ser desfeita.`))return;try{if(u.id)await sbDelete(u.id);db.unidades.splice(i,1);nativeSet(db);alert('Unidade excluída com sucesso.');window.location.reload()}catch(e){console.error(e);alert('Não foi possível excluir esta unidade. Se ela possuir demandas vinculadas, remova ou altere essas demandas antes de excluir.')}}
function bind(){if(!isUnitsPage())return;addDeleteButtons();const search=document.querySelector('#moduleSearch');if(search&&!search.dataset.unitDeleteBound){search.dataset.unitDeleteBound='1';search.addEventListener('input',()=>setTimeout(addDeleteButtons,30))}}
const schedule=()=>setTimeout(bind,80);document.addEventListener('click',e=>{if(e.target.closest('[data-view]'))schedule()});window.addEventListener('hashchange',schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();
})();